Przeniesienie danych na one drive
PiotrMaciejKowalski/BigData2022-films pull request #24
Opened 2022-12-13 15:23 UTC by Naunn

2022-12-13 15:57 UTC, PiotrMaciejKowalski commented on lib/pyspark_startup.py
> +def load(spark: SparkSession, path: str = "") -> DataFrame:
A nie brakuje Ci zmian w pliku `data_source.sh`?

2022-12-13 18:10 UTC, Naunn commented on lib/pyspark_startup.py
> +def load(spark: SparkSession, path: str = "") -> DataFrame:
Niekoniecznie. Plik bash "Data_source.sh" pobierał dane do zasobów colab'a, a teraz wskazany jest bezpośrednio folder z tymi danymi na google drive-ie.

2022-12-14 17:29 UTC, PiotrMaciejKowalski commented on lib/pyspark_startup.py
> +def load(spark: SparkSession, path: str = "") -> DataFrame:
Fajnie, ale może powinien te dane zapisać w odpowiedniej lokacji ?

2022-12-14 20:54 UTC, Naunn commented on lib/pyspark_startup.py
> +def load(spark: SparkSession, path: str = "") -> DataFrame:
Nie rozumiem. Proszę o wyjaśnienie w czym jest problem.

2022-12-14 22:02 UTC, PiotrMaciejKowalski requested changes

2022-12-14 22:02 UTC, PiotrMaciejKowalski commented on lib/pyspark_startup.py
> +def load(spark: SparkSession, path: str = "") -> DataFrame:
Ok obecnie zmieniamy 
```
<---
 title_basics = spark.read.csv("title.basics.tsv.gz", sep="\t", header=True).drop(
 ---
    title_basics = spark.read.csv(path+"title.basics.tsv.gz", sep="\t", header=True).drop(
--->
```

Czyli wszystkie pliki źródłowe mają być w katalogu path. Ale skrypt `data_source.sh` dalej pobiera je do głównego katalogu. Wypadałoby je przenieść w tym skrypcie do lokalizacji z której będą używane.

2022-12-15 21:16 UTC, Naunn commented on lib/pyspark_startup.py
> +def load(spark: SparkSession, path: str = "") -> DataFrame:
Zmodyfikowałem plik bash

2022-12-16 12:58 UTC, PiotrMaciejKowalski requested changes

2022-12-16 12:58 UTC, PiotrMaciejKowalski commented on data_source.sh
> +wget "https://datasets.imdbws.com/name.basics.tsv.gz" -O /content/drive/.shortcut-targets-by-id/1VcOir9FMG8LzEsUE-Q8YA79c_sV0tJwp/bigdata2022/name.basics.tsv.gz
Spróbuj tego i daj warunkowanie
```
DIR=/tmp/downloads
if [ -d "$DIR" ];
then
    echo "$DIR directory exists."
else
	echo "$DIR directory does not exist."
fi
```
https://linuxconfig.org/bash-scripting-check-if-directory-exists

2022-12-17 14:00 UTC, Naunn commented on data_source.sh
> +wget "https://datasets.imdbws.com/name.basics.tsv.gz" -O /content/drive/.shortcut-targets-by-id/1VcOir9FMG8LzEsUE-Q8YA79c_sV0tJwp/bigdata2022/name.basics.tsv.gz
Dodano, działa

2022-12-18 10:22 UTC, PiotrMaciejKowalski approved these changes

2022-12-18 10:22 UTC, merged