Pogrupowanie danych
PiotrMaciejKowalski/BigData2022-films pull request #29
Opened 2022-12-18 14:36 UTC by kamilkolo22

Dodałem funkcję normalizującą dane w wybranych kolumnach według grup.

2022-12-18 20:49 UTC, PiotrMaciejKowalski requested changes

2022-12-18 20:49 UTC, PiotrMaciejKowalski commented on lib/pyspark_preprocesing.py
> +        "stddev(" + x + ") as stdev_" + x + ", avg(" + x + ") as avg_" + x
nie jestem fanem robienia tego za pomocą sql-a ale zostawiłem tę możliwość i masz prawo do tego wyboru. Ale rozważ chociaż użycie f-stringów by czytelniej zapisać swój kod
```suggestion
       f'stddev({x}) as stdev_{x}, avg({x}) as avg_{x}' 
```

2022-12-18 22:11 UTC, kamilkolo22 commented on lib/pyspark_preprocesing.py
> +        "stddev(" + x + ") as stdev_" + x + ", avg(" + x + ") as avg_" + x
Chciałem żeby ta funkcja była jak najbardziej uniwersalna a zrobienie tego w sql wydało mi się prostszym rozwiązaniem. Dodałem f-stringi tam gdzie było można

2022-12-18 22:24 UTC, Naunn approved these changes

2022-12-22 16:15 UTC, PiotrMaciejKowalski approved these changes

2022-12-22 16:15 UTC, merged