Dodany plik markdown z opisem metryki
PiotrMaciejKowalski/BigData2022-films pull request #38
Opened 2022-12-22 21:50 UTC by dommar4

2022-12-23 13:10 UTC, PiotrMaciejKowalski requested changes

2022-12-23 13:10 UTC, PiotrMaciejKowalski commented on docs/Research metryk.md
> +```angular2html
usunąć tag

2022-12-23 17:21 UTC, dommar4 commented on docs/Research metryk.md
> +```angular2html
Usunięty

2022-12-27 16:50 UTC, PiotrMaciejKowalski approved these changes

2022-12-27 18:33 UTC, merged