Poprawa miary IoU
PiotrMaciejKowalski/BigData2022-films pull request #52
Opened 2023-01-19 22:51 UTC by janostalski

2023-01-19 23:45 UTC, kamilkolo22 requested changes

2023-01-19 23:45 UTC, kamilkolo22 commented on lib/metrics.py
> +    if None in list_1:
ten if jest raczej niepotrzebny, możesz zostawić samo list_1 = list(filter(None, list_1))

2023-01-20 08:29 UTC, janostalski commented on lib/metrics.py
> +    if None in list_1:
poprawione

2023-01-20 11:11 UTC, kamilkolo22 approved these changes

2023-01-20 11:11 UTC, merged